compute_environment: LOCAL_MACHINE
distributed_type: FSDP  # 声明使用FSDP
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP # 或 SIZE_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_sharding_strategy: FULL_SHARD # 1表示分片参数，2表示分片参数+梯度，FULL_SHARD最节省内存
  fsdp_state_dict_type: SHARDED_STATE_DICT
machine_rank: 0
main_process_port: 29501
mixed_precision: 'bf16' # H100上使用bf16
num_machines: 1
num_processes: 4 # 你的GPU数量
use_cpu: false